"""
Django settings for demo project.

Generated by 'django-admin startproject' using Django 3.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# 工程根目录
BASE_DIR = Path(__file__).resolve().parent.parent
print("BASE_DIR",BASE_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 秘钥,方便后期加密使用
SECRET_KEY = '#@)-!_$l-vc&zeu72)_o@02_)t28@q)%irq7v8ckoun!w&ip75'

# SECURITY WARNING: don't run with debug turned on in production!
# django默认开启调试，将来上线改为False,
# 如果不再是调试环境，Django不再提供静态文件访问支持。
DEBUG = True

# 允许那些域名访问
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 如果应用中定义的模型，并要做迁移建表时，必须注册、安装应用，
    # 如果应用中只有视图和路由这些代码应用可注册，可不注册
    # 如果因用中使用模板劲量注册
    'users.apps.UsersConfig',

]

# 中间件，监听请求响应中间过程
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware', #禁用CSRF认证，不然没发测试POST,PUT,DELETE 请求
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 工程路由入口文件:总路由
ROOT_URLCONF = 'demo.urls'

# 工程模板配置项
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# 项目上线后的文件启动入口
WSGI_APPLICATION = 'demo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases


# 项目数据库配置项
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

# 密码认证配置项
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

# 本地化
# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-hans'

# 时区
# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/ShangHai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

# 静态文件访问路径前缀
STATIC_URL = '/static/'

# 127.0.0.1:8003/static/123.bmp
# http://127.0.0.1:8003/static/hello/123.bmp
STATICFILES_DIRS = [
    # 'E:\eric\py_virtualenv\py_django\demo\static_files'
     os.path.join(BASE_DIR,'static_files'),
     os.path.join(BASE_DIR,'static_files/hello')

]
